#!/usr/bin/env python3
"""
Generate a VOACAP (voacapl) point-to-point input file, run the prediction,
and parse the resulting output into a compact hour-by-frequency summary.

This talks to the 'voacapl' binary built from jawatson/voacapl (cloned and
built by setup.sh into vendor/voacapl). It writes a fixed-column-format
VOACAP "ASCII CARD" input file (the same format voacapl itself writes when
saving a circuit), matching the exact FORTRAN format strings used in
src/voacapw/voacap.for of that project.
"""
import argparse
import math
import os
import re
import shutil
import subprocess
import sys
import time
import uuid


# voacapl's ANTCALC subroutine (src/voacapw/antcalc.for) reads the
# propagation-input filename it's given into a FORTRAN CHARACTER*20 dummy
# argument. FORTRAN silently truncates an over-length actual argument to
# fit the dummy's declared length rather than raising an error, so a
# longer filename makes ANTCALC's OPEN(status='old') look for a file that
# doesn't exist. ANTCALC then prints a warning to stdout (which nothing
# checks) and returns without regenerating the antenna gain tables
# (gainNN.dat) for the run -- silently leaving antenna choice (ANTENNA
# card) with no effect, since the rest of the run just reads whatever
# gainNN.dat happens to already be on disk. See the "generate_run_tag"
# docstring below and the accompanying unit test in tests/.
ANTCALC_FILENAME_LIMIT = 20


def generate_run_tag():
    """A short, unique tag for this run's input/output filenames.

    Must be short enough that f"{tag}.dat"/f"{tag}.out" stay within
    ANTCALC_FILENAME_LIMIT chars -- see the module-level comment above.
    """
    return "v" + uuid.uuid4().hex[:12]


def f(width, decimals, value):
    """Right-justify a float into a fixed-width Fortran-style field."""
    s = f"{value:.{decimals}f}"
    if len(s) > width:
        raise ValueError(f"value {value!r} does not fit in field width {width}")
    return s.rjust(width)


def i(width, value):
    s = str(int(value))
    if len(s) > width:
        raise ValueError(f"value {value!r} does not fit in field width {width}")
    return s.rjust(width)


def bearing(lat1, lon1, lat2, lon2):
    """Initial great-circle bearing in degrees from point 1 to point 2."""
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dlon = math.radians(lon2 - lon1)
    y = math.sin(dlon) * math.cos(phi2)
    x = math.cos(phi1) * math.sin(phi2) - math.sin(phi1) * math.cos(phi2) * math.cos(dlon)
    return (math.degrees(math.atan2(y, x)) + 360.0) % 360.0


def antenna_field(kind, index, minfreq, maxfreq, antfile, beam, last):
    """Build one ANTENNA card. `last` is tx power (kW) for kind=1, gain (dBi) for kind=2."""
    name = antfile.ljust(21)
    if len(name) > 21:
        raise ValueError(f"antenna file path {antfile!r} longer than 21 chars")
    return (
        "ANTENNA   "
        + i(5, kind) + i(5, index) + i(5, minfreq) + i(5, maxfreq)
        + f(10, 3, 0.0)
        + "[" + name + "]"
        + f(5, 1, beam)
        + f(10, 4, last)
    )


def build_input(args):
    lines = []
    lines.append("COMMENT   Generated by the voacap skill")
    lines.append("LINEMAX      55       number of lines-per-page")
    lines.append(f"COEFFS    {args.coeffs}")

    hr1, hr2 = args.hours
    iflag = -1 if args.lmt else 1
    lines.append("TIME      " + i(5, hr1) + i(5, hr2) + i(5, 1) + i(5, iflag))

    lines.append("MONTH     " + i(5, args.year) + f(5, 2, args.month + args.day_fraction))
    lines.append("SUNSPOT   " + f(5, 1, args.ssn))

    tx_name = args.tx_name[:20].ljust(20)
    rx_name = args.rx_name[:20].ljust(20)
    lines.append(f"LABEL     {tx_name}{rx_name}")

    tns = "N" if args.tx_lat >= 0 else "S"
    tew = "E" if args.tx_lon >= 0 else "W"
    rns = "N" if args.rx_lat >= 0 else "S"
    rew = "E" if args.rx_lon >= 0 else "W"
    lines.append(
        "CIRCUIT   "
        + f(5, 2, abs(args.tx_lat)) + tns
        + f(9, 2, abs(args.tx_lon)) + tew
        + f(9, 2, abs(args.rx_lat)) + rns
        + f(9, 2, abs(args.rx_lon)) + rew
        + "  " + "S" + " " + i(5, 0)
    )

    lines.append(
        "SYSTEM    "
        + f(5, 0, 1)
        + f(5, 0, args.noise)
        + f(5, 2, args.min_angle)
        + f(5, 0, args.req_reliability)
        + f(5, 2, args.req_snr)
        + f(5, 2, args.multipath_power)
        + f(5, 2, args.multipath_delay)
    )

    lines.append("FPROB     " + f(5, 2, 1.0) + f(5, 2, 1.0) + f(5, 2, 1.0) + f(5, 2, 0.0))

    tx_beam = args.tx_beam
    rx_beam = args.rx_beam
    if tx_beam is None:
        tx_beam = bearing(args.tx_lat, args.tx_lon, args.rx_lat, args.rx_lon)
    if rx_beam is None:
        rx_beam = bearing(args.rx_lat, args.rx_lon, args.tx_lat, args.tx_lon)

    lines.append(antenna_field(1, 1, 2, 30, args.tx_antenna, tx_beam, args.tx_power_kw))
    lines.append(antenna_field(2, 2, 2, 30, args.rx_antenna, rx_beam, 0.0))

    freqs = list(args.freqs) + [0.0] * (11 - len(args.freqs))
    lines.append("FREQUENCY " + "".join(f(5, 2, v) for v in freqs[:11]))

    lines.append("METHOD    " + i(5, 30) + i(5, 0))
    lines.append("EXECUTE")
    lines.append("QUIT")
    return "\n".join(lines) + "\n"


NUMERIC_RE = re.compile(r"^-?\d+(\.\d+)?$|^-$")


def split_data_label(line):
    parts = line.split()
    idx = 0
    while idx < len(parts) and NUMERIC_RE.match(parts[idx]):
        idx += 1
    return parts[:idx], " ".join(parts[idx:])


def parse_output(text):
    """Parse METHOD 30 tables into: [{hour, lmt, freqs: [{freq, rel, snr, mufday, loss}, ...]}]"""
    lines = text.splitlines()
    blocks = []
    n = len(lines)
    idx = 0
    while idx < n:
        data, label = split_data_label(lines[idx])
        if label == "FREQ" and len(data) >= 3:
            hour, muf = data[0], data[1]
            # Data rows are [MUF, f1..fN]; user frequencies start at column 1.
            freqs = [float(v) for v in data[2:13]]
            rows = {}
            j = idx + 1
            while j < n and lines[j].strip():
                d, lab = split_data_label(lines[j])
                if lab:
                    rows[lab] = d
                j += 1
            entries = []
            for k, fr in enumerate(freqs):
                if fr <= 0.0:
                    continue

                def val(label_name, cast=float):
                    row = rows.get(label_name)
                    col = k + 1
                    if row is None or col >= len(row) or row[col] == "-":
                        return None
                    try:
                        return cast(row[col])
                    except ValueError:
                        return None

                entries.append({
                    "freq_mhz": fr,
                    "mode": val("MODE", str),
                    "rel": val("REL"),
                    "snr_db": val("SNR"),
                    "mufday": val("MUFday"),
                    "loss_db": val("LOSS"),
                    "s_dbw": val("S DBW"),
                })
            blocks.append({"hour": float(hour), "muf_mhz": float(muf), "freqs": entries})
            idx = j
        else:
            idx += 1
    return blocks


def find_voacapl():
    path = shutil.which("voacapl")
    if path:
        return path
    for candidate in (
        os.path.join(os.path.dirname(__file__), "..", "..", "..", "..", "local", "bin", "voacapl"),
    ):
        candidate = os.path.abspath(candidate)
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate
    return None


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--itshfbc", default=os.path.expanduser(
        os.environ.get("VOACAP_ITSHFBC", "~/itshfbc")))
    p.add_argument("--voacapl-bin", default=None)

    p.add_argument("--tx-name", required=True)
    p.add_argument("--tx-lat", type=float, required=True)
    p.add_argument("--tx-lon", type=float, required=True, help="+E / -W")
    p.add_argument("--rx-name", required=True)
    p.add_argument("--rx-lat", type=float, required=True)
    p.add_argument("--rx-lon", type=float, required=True, help="+E / -W")

    p.add_argument("--year", type=int, default=time.gmtime().tm_year)
    p.add_argument("--month", type=int, required=True, help="1-12")
    p.add_argument("--day-fraction", type=float, default=0.0,
                    help="0.00 = monthly median. Use e.g. 0.50 for mid-month specific-day runs.")
    p.add_argument("--ssn", type=float, default=100.0,
                    help="Smoothed sunspot number. Caller should supply an up-to-date/predicted "
                         "value; this tool does not fetch one.")

    p.add_argument("--hours", type=int, nargs=2, default=[1, 24], metavar=("START", "END"))
    p.add_argument("--lmt", action="store_true", help="Hours are local mean time (default: UTC)")

    p.add_argument("--freqs", type=float, nargs="+", required=True,
                    help="Up to 11 frequencies in MHz")

    p.add_argument("--tx-power-kw", type=float, default=0.1)
    p.add_argument("--tx-antenna", default="default/const17.voa")
    p.add_argument("--rx-antenna", default="default/swwhip.voa")
    p.add_argument("--tx-beam", type=float, default=None,
                    help="Degrees; default is computed great-circle bearing to rx")
    p.add_argument("--rx-beam", type=float, default=None,
                    help="Degrees; default is computed great-circle bearing to tx")

    p.add_argument("--noise", type=float, default=145.0,
                    help="Man-made noise magnitude; result is -noise dBW at 3 MHz "
                         "(145=quiet/suburban, 150=quiet rural, 164=remote, 140.4=residential)")
    p.add_argument("--min-angle", type=float, default=3.0, help="Minimum takeoff angle, degrees")
    p.add_argument("--req-reliability", type=float, default=50.0, help="Required reliability, %%")
    p.add_argument("--req-snr", type=float, default=24.0, help="Required SNR, dB")
    p.add_argument("--multipath-power", type=float, default=3.0, help="dB")
    p.add_argument("--multipath-delay", type=float, default=0.10, help="ms")
    p.add_argument("--coeffs", choices=["CCIR", "URSI"], default="CCIR")

    p.add_argument("--input-file", default=None,
                    help="Defaults to a name unique to this process, under itshfbc/run")
    p.add_argument("--output-file", default=None)
    p.add_argument("--run-dir", default=None)
    p.add_argument("--absorption-mode", choices=["W", "I", "A", "a"], default=None)
    p.add_argument("--json", action="store_true", help="Print parsed JSON instead of a table")
    p.add_argument("--keep-files", action="store_true",
                    help="Do not delete the generated input/output files afterwards")
    return p.parse_args()


def main():
    args = parse_args()

    voacapl_bin = args.voacapl_bin or find_voacapl()
    if not voacapl_bin:
        print("error: could not find the 'voacapl' binary. Build it first "
              "(see .claude/skills/voacap/scripts/setup.sh) or pass --voacapl-bin.",
              file=sys.stderr)
        return 1

    itshfbc = os.path.expanduser(args.itshfbc)
    run_dir = os.path.expanduser(args.run_dir) if args.run_dir else os.path.join(itshfbc, "run")
    if not os.path.isdir(run_dir):
        print(f"error: run directory not found: {run_dir}\n"
              f"Has 'makeitshfbc' been run to set up {itshfbc}?", file=sys.stderr)
        return 1

    tag = generate_run_tag()
    input_file = args.input_file or f"{tag}.dat"
    output_file = args.output_file or f"{tag}.out"

    # A caller-supplied --input-file isn't covered by generate_run_tag()'s
    # own length budget -- guard it explicitly so an over-length name fails
    # loudly here instead of silently disabling antenna gain (see
    # ANTCALC_FILENAME_LIMIT above).
    if args.input_file and len(args.input_file) > ANTCALC_FILENAME_LIMIT:
        print(f"error: --input-file {args.input_file!r} is longer than "
              f"{ANTCALC_FILENAME_LIMIT} characters; voacapl's ANTCALC "
              "subroutine silently truncates and mis-opens longer names, "
              "which disables antenna gain for the run. Use a shorter name.",
              file=sys.stderr)
        return 1

    input_path = os.path.join(run_dir, input_file)
    output_path = os.path.join(run_dir, output_file)

    if len(args.freqs) > 11:
        print("error: at most 11 frequencies are supported", file=sys.stderr)
        return 1

    with open(input_path, "w") as fh:
        fh.write(build_input(args))

    cmd = [voacapl_bin, "-s"]
    if args.run_dir:
        cmd.append(f"--run-dir={run_dir}")
    if args.absorption_mode:
        cmd.append(f"--absorption-mode={args.absorption_mode}")
    cmd += [itshfbc, input_file, output_file]

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)

    if result.returncode != 0 or not os.path.isfile(output_path):
        print("error: voacapl run failed", file=sys.stderr)
        print(result.stdout, file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        return 1

    with open(output_path) as fh:
        out_text = fh.read()

    blocks = parse_output(out_text)

    if not args.keep_files:
        for p in (input_path, output_path):
            try:
                os.remove(p)
            except OSError:
                pass

    if args.json:
        import json
        print(json.dumps({
            "tx": {"name": args.tx_name, "lat": args.tx_lat, "lon": args.tx_lon},
            "rx": {"name": args.rx_name, "lat": args.rx_lat, "lon": args.rx_lon},
            "year": args.year, "month": args.month, "ssn": args.ssn,
            "hours": blocks,
        }, indent=2))
        return 0

    time_label = "LMT" if args.lmt else "UTC"
    print(f"VOACAP prediction: {args.tx_name} -> {args.rx_name}  "
          f"({args.year}-{args.month:02d}, SSN={args.ssn:g})")
    print(f"{'Hour':>5} {'Best MHz':>9} {'REL':>5} {'SNR dB':>7}   Frequencies (REL/SNR)")
    for block in blocks:
        usable = [e for e in block["freqs"] if e["rel"] is not None]
        best = max(usable, key=lambda e: (e["rel"], e["snr_db"] or -999), default=None)
        detail = ", ".join(
            f"{e['freq_mhz']:.2f}={e['rel']:.2f}/{e['snr_db']:.0f}"
            if e["rel"] is not None and e["snr_db"] is not None else f"{e['freq_mhz']:.2f}=-"
            for e in block["freqs"]
        )
        hour_label = block["hour"]
        if best:
            print(f"{hour_label:5.1f} {best['freq_mhz']:9.2f} {best['rel']:5.2f} "
                  f"{best['snr_db']:7.0f}   {detail}")
        else:
            print(f"{hour_label:5.1f} {'--':>9} {'--':>5} {'--':>7}   {detail}")
    print(f"\n({time_label} hours; REL = predicted circuit reliability 0-1, "
          f"SNR = predicted signal-to-noise ratio in dB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
